apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmm
  namespace: 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mmm
  template:
    metadata:
      labels:
        app: mmm
    spec:
      containers:
        # - image: gabtec/test-k8s:v1
        - image: gabtec/test-k8s
          name: mmm
          ports:
            - containerPort: 80
